[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "14"
  ## https://github.com/sveltejs/kit/issues/2687

[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
  publish = "build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["mdsvex"]

[[headers]]
  ## https://answers.netlify.com/t/content-type-header-not-working-in-netlify-toml/7718
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=4000"
    # cache just over 1 hour for webpagetest to be happy
    X-Content-Type-Options = "nosniff"
    ## Content-Security-Policy = "default-src 'self'; script-src 'nonce-jackspiva'; img-src *"
